name: Pruebas unitarias
on:
 push:
     branches:
         - 'testing_**'
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '(Azul)') && contains(github.ref, 'integration') }}
        echo "RAMA INVOCADA ----> ${{ github.ref }}"
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Configuración de entorno de python
      uses: actions/setup-python@v3
      with:
          python-version: '3.9'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: |
        python -m unittest -v tests/test_persona.py
        python -m unittest -v tests/test_perro.py
    - name:  Cubrimiento personalizado
      id: cubrimiento
      run: |
          coverage run -m unittest tests/*.py
          coverage report -m
          
