name: Pruebas unitarias
on:
 push:
     branches:
         - 'testing_**'
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '(Azul)') && contains(github.ref,'integration') }}
    steps:
    - name: Printing variables
      run: |
       echo "RAMA INVOCADA ----> ${{ github.ref }}"
       echo "MENSAJE COMMIT ----> ${{ github.event.head_commit.message }}"
       
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: |
        python -m unittest -v 
    - name:  Cubrimiento personalizado
      id: cubrimiento
      run: |
          coverage run -m unittest 
          coverage report -m
           
  automerge:
    needs: job1
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.head_commit.message,'[release]')}}
    steps:
     - name: Mezcla ${{ github.ref }} -> develop
       uses: tukasz/direct-merge-action@master
       with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         source-branch: ${{ github.ref }}
         target-branch: develop
         commit-message: "Se actualiza develop con la rama ${{ github.ref }}"
         
  release:
    needs: job1
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.event.head_commit.message,'[release]')}}
    steps:
     - name: Mezcla ${{ github.ref }} -> develop
       uses: tukasz/direct-merge-action@master
       with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         source-branch: ${{ github.ref }}
         target-branch: develop
         commit-message: "Listo para liberar [release]"
         
     - name: Sleep for 3s
       uses: juliangruber/sleep-action@v1
       with:
         time: 3s
         
         
  invoke_workflow:
    needs: release
    permissions: write-all
    if: ${{ endsWith(github.event.head_commit.message,'[release]')}}   
    uses: fanpay/git_actions/.github/workflows/release.yml@main
         
