name: Hola mundo
on:
  push:
    branches: [ main ]  #rama o ramas específicas donde se espera el evento ocurra
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest #S.O donde se ejecutará el job
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo
      run: |
        echo $MI_VARIABLE.
