name: Creating release version
on:
 push:
     branches: [develop]
jobs:
  job1:
    name: Pruebas
    if: ${{ endsWith(github.event.head_commit.message, '(Azul)') && contains(github.ref,'integration') && contains(github.event.head_commit.message, '[ready_to_merge]')}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:     
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: |
        python -m unittest -v 
    - name:  Cubrimiento personalizado   
      id: cubrimiento
      run: |
          coverage run -m unittest
          coverage report --fail-under=98  
     
    - name: Printing coverage result
      run: |
       echo "RAMA INVOCADA ----> ${{ github.event.head_commit.message }}"
       echo "MENSAJE COMMIT ----> ${{ github.event.head_commit.message }}"
           
    
    

