name: Creating release version
on: 
 push:
     branches:
         - develop

jobs:
  testinggg:
   permissions: write-all
   runs-on: ubuntu-latest
   steps:
    - name: Imprimir mensajes
      run: |
        echo "COMMIT MENSAJE ----> ${{ github.event.head_commit.message }}"
        echo "EVENT ----> ${{ github.event }}"
        
  release:
   permissions: write-all
   runs-on: ubuntu-latest
   if: ${{ endsWith(github.event.head_commit.message, '[release]') }}
   steps:
    - name: Crear rama
      run: |
        git checkout develop
        git checkout -b release/1.0.0
        git push -f -u origin release/1.0.0
    - name: Mezcla develop -> release
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: release/1.0.0
        commit-message: "Se actualiza la rama release con la rama develop. Release is ready to merge in main!"
  job1:
    needs: release
    name: Pruebas
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:     
    - name: Printing variables
      run: |
       echo "RAMA INVOCADA ----> ${{ github.ref }}"
       echo "MENSAJE COMMIT ----> ${{ github.event.head_commit.message }}"
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: |
        python -m unittest -v 
    - name:  Cubrimiento personalizado   
      id: cubrimiento
      run: |
          coverage run -m unittest
          coverage report --fail-under=98  
     
    - name: Printing coverage result
      run: |
       echo "RAMA INVOCADA ----> ${{ github.event.head_commit.message }}"
       echo "MENSAJE COMMIT ----> ${{ github.event.head_commit.message }}"
       
    - name: Mezcla release -> main
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: release/1.0.0
        target-branch: main
        commit-message: "Se integra rama release version 1.0.0 en main. Integración lista"
           
    
    
